### ISSUE TITLE
[Issue] Crazy Crates Quest BUG

### ISSUE THREAD

**Issue by NaTorOG** [GC-spigot/battle-pass#247]
**Describe the bug**
Opening a Crate for the CrazyCraft_Open quest get counted 2 times instead of one time.

**To Reproduce**
Open a Crate of Crazy Crates that is Cosmic Type

**Server Information (please complete the following information):**
- Server Version: [e.g. Pufferfish+ 1.19.2]
- Plugin Version: [e.g.3.12.7]

**Comment by NaTorOG** [comment]
Any update???
Now its even worse

**Comment by GC-spigot** [comment]
How were you counting? It's very obvious what the problem is, it's not "even worse" or "better". Every time a reward is claimed quest is processed. 

I cannot do anything, CrazyCrates changed their api and now it doesn't have an event/trigger when crates are opened, only when reward is given. 

This is caused by CrazyCrates, not my plugin. Ask them to add an event API when crate is opened not reward is claimed.
