### ISSUE TITLE
UUID support for offline server

### ISSUE THREAD

**Issue by LPPRRR** [GC-spigot/battle-pass#374]
### Describe the feature

Players with offline servers who drop offline will have all pass levels reset due to UUID. 
Can you come up with a storage method based on player id?

**Comment by KPGTB** [comment]
Hey! Can you describe what you exactly mean? If the server supports cracked accounts, then players with purchased Minecraft will still have cracked UUID. The only problem can appear when you use any plugin to modify UUIDs of players. Anyway, the best fix for that problem is to not support **cracked** accounts
