### ISSUE TITLE
Lags when opening quests menu (caused by progress bar)

### ISSUE THREAD

**Issue by dinobossytnew** [GC-spigot/battle-pass#581]
### Describe the bug

I found a memory leak in the Battle Pass menus and I want you to urgently review it. This could be a very poor implementation on your part in the daily missions menu.

### How to reproduce

Using my config or the default plugin config, go to the daily missions menu with a right-click. You will see the time it takes for the plugin to respond with Spark.

my spark
https://spark.lucko.me/rpiatdyPiS

### Screenshots / Videos

https://vimeo.com/995875914

### Server Log

https://mcpaste.io/b97fe03cd6007865

**Comment by KPGTB** [comment]
Hey! Can you send me these files:

1) `daily-quests/daily-data.json`
2) `quests/daily-quests.yml`
3) Data of users which have this problem (file save method - `users/UUID_OF_THATT_USER.json` | MySQL save method - row with UUID of user in table `battlepass-users` )

**Comment by dinobossytnew** [comment]
I do not use mysql at the moment as I am in the testing phase.
https://mclo.gs/8GksOQD daily-quests.yml
https://mclo.gs/sKlVYqG daily-data.json

**Comment by dinobossytnew** [comment]
https://mclo.gs/DErk4G8 user 1
https://mclo.gs/QFEUq1P user 2

**Comment by dinobossytnew** [comment]
the video was made with op so remember I have everything unlocked.

**Comment by KPGTB** [comment]
I found the issue which caused that problem. It seems that you (7b5e0b5a-ffac-4330-b264-5348fd00b77e) progressed daily quest with ID 5 to 792 points and after that you probably changed this quest to login quest with required progress 1. It caused a problem, because the plugin wanted to create a progress bar with 792%. The fix will be available in the next update. You can also manually fix it by deleting your current data (/bpa delete user)
